# Generated by Django 4.2.4 on 2024-05-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
