# Generated by Django 4.2.4 on 2024-05-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_alter_booksborrowed_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksborrowed',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=10),
        ),
    ]
